#!/usr/bin/env bash

# shellcheck disable=2155

declare -gx BASH_REST_DASHBOARD_PROJECT_BASE_DIRECTORY="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"

declare -gx BASH_REST_DASHBOARD_HTTP_BASE_DIRECTORY="${BASH_REST_DASHBOARD_PROJECT_BASE_DIRECTORY}/http"
declare -gx BASH_REST_DASHBOARD_CONTENT_TYPES_BASE_DIRECTORY="${BASH_REST_DASHBOARD_HTTP_BASE_DIRECTORY}/content-types"
declare -gx BASH_REST_DASHBOARD_RESPONSES_BASE_DIRECTORY="${BASH_REST_DASHBOARD_HTTP_BASE_DIRECTORY}/responses"

declare -gx BASH_REST_DASHBOARD_PAGES_BASE_DIRECTORY="${BASH_REST_DASHBOARD_PROJECT_BASE_DIRECTORY}/pages"

declare -gx BASH_REST_DASHBOARD_STYLES_BASE_DIRECTORY="${BASH_REST_DASHBOARD_PROJECT_BASE_DIRECTORY}/src/styles"

declare -gx BASH_REST_DASHBOARD_APP_BASE_DIRECTORY="${BASH_REST_DASHBOARD_PROJECT_BASE_DIRECTORY}/src/app"

declare -a BASH_REST_DASHBOARD_CONTROLLERS

load_controllers() {
	mapfile -d $'\0' BASH_REST_DASHBOARD_CONTROLLERS < <(find ./src -type f -name "*.controller.bash" -print0)

	for i in "${!BASH_REST_DASHBOARD_CONTROLLERS[@]}"; do
		BASH_REST_DASHBOARD_CONTROLLERS["${i}"]=$(realpath "${BASH_REST_DASHBOARD_CONTROLLERS[${i}]}")
	done
}

load_controllers

bash ./modules/bash-rest/bash-rest.bash "${BASH_REST_DASHBOARD_CONTROLLERS[@]}" "${BASH_REST_DASHBOARD_PROJECT_BASE_DIRECTORY}/src/override.bash"
